CREATE TABLE SEAT (
  ID         BIGINT AUTO_INCREMENT,
  IS_FREE        BOOLEAN,
  ROW		 INT,
  SEAT      INT,
  EDA_ID    BIGINT,
  PRIMARY KEY (ID),
  FOREIGN KEY (EDA_ID) REFERENCES EVENT_DATE_AND_AUDITORIUM(ID)
);
