CREATE TABLE AUDITORIUM (
  ID         BIGINT AUTO_INCREMENT,
  NAME       VARCHAR(100),
  PRIMARY KEY (ID)
);

INSERT INTO AUDITORIUM(NAME) VALUES('Red');
INSERT INTO AUDITORIUM(NAME) VALUES('Blue');