CREATE TABLE GENRE_EVENT (
	ID      BIGINT AUTO_INCREMENT,
	GENRE_NAME VARCHAR(50),
	EVENT_ID  BIGINT,
	PRIMARY KEY (ID),
	FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID),
	FOREIGN KEY (GENRE_NAME) REFERENCES GENRE(NAME)
);