CREATE TABLE AUDITORIUM (
  ID         BIGINT AUTO_INCREMENT,
  NAME       VARCHAR(100),
  PRIMARY KEY (ID)
);

INSERT INTO AUDITORIUM(ID,NAME) VALUES(1,'Red');
INSERT INTO AUDITORIUM(ID,NAME) VALUES(2,'Blue');