CREATE TABLE AUDITORIUM (
  ID         BIGINT AUTO_INCREMENT,
  NAME       VARCHAR(100),
  ROW_NUM    INTEGER,
  SEATS_IN_ROW INTEGER,
  PRIMARY KEY (ID)
);

INSERT INTO AUDITORIUM(ID,NAME,ROW_NUM,SEATS_IN_ROW) VALUES(1,'Red',5,10);
INSERT INTO AUDITORIUM(ID,NAME,ROW_NUM,SEATS_IN_ROW) VALUES(2,'Blue',7,12);