CREATE TABLE USER_ROLE (
  ID BIGINT AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);