CREATE TABLE SEAT (
  ID         BIGINT AUTO_INCREMENT,
  AUDITORIUM_ID  BIGINT,
  IS_FREE        BOOLEAN,
  IS_VIP            BOOLEAN,
  ROW		 INT,
  SEAT      INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (AUDITORIUM_ID) REFERENCES AUDITORIUM(ID)
);
