CREATE TABLE USER (
  ID BIGINT AUTO_INCREMENT,
  FIRST_NAME varchar(60),
  LAST_NAME varchar(60),
  BIRTHDAY DATE,
  EMAIL varchar(60),
  USERNAME varchar(60),
  PASSWORD varchar(60),
  PASSWORD_CONFIRM varchar(60),
  ACTIVE TINYINT NOT NULL DEFAULT 1 ,
  PRIMARY KEY (ID)
);