CREATE TABLE GENRE (
	NAME   VARCHAR(50),	
	PRIMARY KEY (NAME)
);

INSERT INTO GENRE(NAME) VALUES('Action');
INSERT INTO GENRE(NAME) VALUES('Adventure');
INSERT INTO GENRE(NAME) VALUES('Biography');
INSERT INTO GENRE(NAME) VALUES('Crime');
INSERT INTO GENRE(NAME) VALUES('Documentary');
INSERT INTO GENRE(NAME) VALUES('Drama');
INSERT INTO GENRE(NAME) VALUES('Family');
INSERT INTO GENRE(NAME) VALUES('Fantasy');
INSERT INTO GENRE(NAME) VALUES('History');
INSERT INTO GENRE(NAME) VALUES('Horror');
INSERT INTO GENRE(NAME) VALUES('Musical');
INSERT INTO GENRE(NAME) VALUES('Mystery');
INSERT INTO GENRE(NAME) VALUES('Romance');
INSERT INTO GENRE(NAME) VALUES('Short');
INSERT INTO GENRE(NAME) VALUES('Sport');
INSERT INTO GENRE(NAME) VALUES('War');
INSERT INTO GENRE(NAME) VALUES('Western');