INSERT INTO EVENT (NAME, BASE_PRICE, RATING) VALUES ('Man in Black 3', '150.0', 'HIGH');
INSERT INTO EVENT (NAME, BASE_PRICE, RATING) VALUES ('TOR', '90.0', 'LOW');
INSERT INTO EVENT (NAME, BASE_PRICE, RATING) VALUES ('Predator', '110.0', 'MED');